# Generated by Django 2.2.10 on 2020-04-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bandas',
            fields=[
                ('id_banda', models.AutoField(primary_key=True, serialize=False)),
                ('bool_acabada', models.BooleanField(default=False, verbose_name='Acabada esta semana')),
            ],
            options={
                'verbose_name': 'Banda semanal',
                'verbose_name_plural': 'Bandas semanales',
                'db_table': 'bandas',
                'managed': True,
            },
        ),
    ]
