# Generated by Django 2.2.10 on 2020-04-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas_wow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandas',
            name='tx_nombre',
            field=models.CharField(default='', max_length=100, verbose_name='Nombre de la banda'),
            preserve_default=False,
        ),
    ]
