# Generated by Django 2.2.10 on 2020-04-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas_wow', '0002_bandas_tx_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandas',
            name='tx_expansion',
            field=models.CharField(default='', max_length=32, verbose_name='Expansión de la banda'),
            preserve_default=False,
        ),
    ]
