# Generated by Django 2.1.4 on 2018-12-10 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32, unique=True, verbose_name='Nombre del equipo')),
                ('usuario', models.ForeignKey(db_column='usuario', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Equipo de la liga',
                'db_table': 'equipos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Jornadas',
            fields=[
                ('id_jornada', models.AutoField(primary_key=True, serialize=False)),
                ('num_jornada', models.IntegerField(unique=True, verbose_name='Jornada')),
            ],
            options={
                'verbose_name': 'Jornada de liga',
                'db_table': 'jornadas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Partidos',
            fields=[
                ('id_partido', models.AutoField(primary_key=True, serialize=False)),
                ('puntos_equipo_local', models.IntegerField(verbose_name='Puntos equipo local')),
                ('puntos_equipo_visitante', models.IntegerField(verbose_name='Puntos equipo visitante')),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='equipo_local', to='liga.Equipos')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='equipo_visitante', to='liga.Equipos')),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liga.Jornadas')),
            ],
            options={
                'verbose_name': 'Partidos de liga',
                'db_table': 'partidos',
                'managed': True,
            },
        ),
    ]
