# Generated by Django 2.1.4 on 2018-12-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipos',
            options={'managed': True, 'verbose_name': 'Equipo de la liga', 'verbose_name_plural': 'Equipos de la liga'},
        ),
        migrations.AlterModelOptions(
            name='jornadas',
            options={'managed': True, 'verbose_name': 'Jornada de liga', 'verbose_name_plural': 'Jornadas de liga'},
        ),
        migrations.AlterModelOptions(
            name='partidos',
            options={'managed': True, 'verbose_name': 'Partido de liga', 'verbose_name_plural': 'Partidos de liga'},
        ),
        migrations.AlterField(
            model_name='partidos',
            name='puntos_equipo_local',
            field=models.IntegerField(default=0, verbose_name='Puntos equipo local'),
        ),
        migrations.AlterField(
            model_name='partidos',
            name='puntos_equipo_visitante',
            field=models.IntegerField(default=0, verbose_name='Puntos equipo visitante'),
        ),
    ]
