# Generated by Django 2.1.4 on 2018-12-10 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0002_auto_20181210_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partidos',
            name='equipo_local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='equipo_local', to='liga.Equipos', verbose_name='equipo_local'),
        ),
        migrations.AlterField(
            model_name='partidos',
            name='equipo_visitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='equipo_visitante', to='liga.Equipos', verbose_name='equipo_visitante'),
        ),
        migrations.AlterField(
            model_name='partidos',
            name='jornada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liga.Jornadas', verbose_name='jornada'),
        ),
    ]
