# Generated by Django 2.1.4 on 2018-12-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0003_auto_20181210_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornadas',
            name='jornada_jugada',
            field=models.BooleanField(default=False, verbose_name='Jornada ya jugada'),
        ),
    ]
